<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\UserController:index' => function () {
    return ($this->privates['service_locator.9tQ0VwG'] ?? $this->load(__DIR__.'/getServiceLocator_9tQ0VwGService.php'));
}, 'App\\Controller\\ViewController:index' => function () {
    return ($this->privates['service_locator.LGvl3YC'] ?? $this->load(__DIR__.'/getServiceLocator_LGvl3YCService.php'));
}, 'App\\Controller\\ViewController:indexResearch' => function () {
    return ($this->privates['service_locator.LGvl3YC'] ?? $this->load(__DIR__.'/getServiceLocator_LGvl3YCService.php'));
}, 'App\\Controller\\UserController::index' => function () {
    return ($this->privates['service_locator.9tQ0VwG'] ?? $this->load(__DIR__.'/getServiceLocator_9tQ0VwGService.php'));
}, 'App\\Controller\\ViewController::index' => function () {
    return ($this->privates['service_locator.LGvl3YC'] ?? $this->load(__DIR__.'/getServiceLocator_LGvl3YCService.php'));
}, 'App\\Controller\\ViewController::indexResearch' => function () {
    return ($this->privates['service_locator.LGvl3YC'] ?? $this->load(__DIR__.'/getServiceLocator_LGvl3YCService.php'));
})));
