<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\GroupController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/GroupController.php';

return $this->services['App\Controller\GroupController'] = new \App\Controller\GroupController();
