<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator._zFg.Kc' shared service.

return $this->privates['service_locator._zFg.Kc'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('doctrine' => function () {
    return ($this->services['doctrine'] ?? $this->getDoctrineService());
}, 'router' => function () {
    return ($this->services['router'] ?? $this->getRouterService());
}));
