<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.LGvl3YC' shared service.

return $this->privates['service_locator.LGvl3YC'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('doctrine' => function () {
    return ($this->services['doctrine'] ?? $this->getDoctrineService());
}, 'es' => function (): ?\App\Service\EntityService {
    return ($this->privates['App\Service\EntityService'] ?? $this->load(__DIR__.'/getEntityServiceService.php'));
}, 'formfactory' => function () {
    return ($this->services['form.factory'] ?? $this->load(__DIR__.'/getForm_FactoryService.php'));
}, 'twig' => function () {
    return ($this->services['twig'] ?? $this->getTwigService());
}));
