<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7I9Lsx4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7I9Lsx4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7I9Lsx4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7I9Lsx4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container7I9Lsx4\srcDevDebugProjectContainer();
